name: deploy

# 代码提交到main分支时触发github action
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Web
        run: hugo -D

      - name: Create or Update CNAME File
        run:
          # 检查 CNAME 文件是否存在
          if [ ! -f "./public/CNAME" ]; then
          echo "Creating CNAME file..."
          echo "wzwannet.cn" > ./public/CNAME
          else
          echo "Updating CNAME file..."
          # 你可以在这里根据需要修改 CNAME 文件的内容
          echo "wzwannet.cn" > ./public/CNAME
          fi
      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v4
        with:
          PERSONAL_TOKEN: ${{ secrets.BLOG }}
          EXTERNAL_REPOSITORY: wzwan-developer/wzwan-developer.github.io
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./public
          commit_message: auto deploy